services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: campeonato_futebol
    volumes:
      - ./init:/docker-entrypoint-initdb.d